### ISSUE TITLE
Add instruction how to build chromium with custom hangouts flag

### ISSUE THREAD

**Issue by mjenczmyk** [avivace/deb-builds#2]
Hi,

I've been using your build of Chromium for a while (Google Hangouts worked there for me, apart from official Chromium builds), unfortunately it's quite old now (your build is based on Chromium 63, the current version is 69 now). Could you describe how can I compile the package with hangouts flag myself, so I could keep the browser I use up to date?

I'm not sure how to do that, to be honest I've never compiled the packages myself, I usually use repositories with already compiled packaged. Even the list of commands you run could help, I should be able to debug further problems myself (or extend your description and prepare pull request to this repository if you want that).

**Comment by Tyler-2** [comment]
What I expected to be able to do was download the files here:
https://github.com/avivace/deb-builds/tree/master/chromium_hangouts

Put them in the same folder, and go. Not quite... because the rules file has to be in the source folder for the build. So I copied it there after the initial run failed.

But the rules file, which is, as far as I can tell, the magic here, as it specifies        
> enable_hangout_services_extension=true \

is giving me:
> debian/rules:103: recipe for target 'override_dh_auto_build-arch' failed
> make[1]: *** [override_dh_auto_build-arch] Error 1
> make[1]: Leaving directory '/home/tyler/chromium/chromium-browser-62.0.3202.89'
> debian/rules:86: recipe for target 'binary' failed
> make: *** [binary] Error 2
> dpkg-buildpackage: error: fakeroot debian/rules binary subprocess returned exit status 2
> debuild: fatal error at line 1152:
> dpkg-buildpackage -rfakeroot -us -uc -ui -b failed

Build process is a little bit of voodoo to me as it is, I'm not likely to figure this out. If I did, I would share exactly what was done to make it work.

**Comment by avivace** [comment]
For some reason I never recevied a mail or a notification for this thread.
I'll get back as soon as possibile explaining how to apply those rules.

**Comment by avivace** [comment]
Check the [release](https://github.com/avivace/deb-builds/releases/tag/jul18-1)
@mjenczmyk @Tyler-2

**Comment by mjenczmyk** [comment]
Thanks @avivace, I'll try the package today.

**Comment by mjenczmyk** [comment]
Would you be able to find time to write what should one do to compile Chromium with those custom flags? Screen sharing still doesn't work in packages from official Debian repository.

**Comment by avivace** [comment]
The https://github.com/avivace/deb-builds/blob/master/chromium_hangouts/build.sh file in the chromium folder is exactly what I do to build the package, just be sure to pull the rules file from this repo 
(https://github.com/avivace/deb-builds/blob/master/chromium_hangouts/rules) and replace with the default one
